/**
 * NetSage AI — Presentation UI  (TASK-014 Polish Pass)
 * dashboard/app.js
 *
 * READ-ONLY presentation layer.
 * All data comes from window.NETSAGE_DATA (generated by build_data_bridge.py).
 * No Gemini calls · No pipeline execution · No data modification.
 */

'use strict';

/* ── Guard ─────────────────────────────────────────────────────────────── */
if (typeof window.NETSAGE_DATA === 'undefined') {
  document.body.innerHTML = `
    <div style="display:flex;align-items:center;justify-content:center;height:100vh;
                flex-direction:column;gap:16px;color:#f87171;font-family:system-ui;padding:20px">
      <div style="font-size:36px">⚠️</div>
      <h2 style="font-size:18px">data.js not found</h2>
      <p style="color:#828fa8;max-width:420px;text-align:center;line-height:1.6;font-size:13px">
        Run <code style="background:#141826;padding:3px 8px;border-radius:4px;color:#9aaad4">
        python dashboard/build_data_bridge.py</code> from the project root, then reload this page.
      </p>
    </div>`;
  throw new Error('NETSAGE_DATA not loaded — run build_data_bridge.py first');
}

const D = window.NETSAGE_DATA;

/* ── Global State ──────────────────────────────────────────────────────── */
let selectedCaseId = null;      // single source of truth for selected case
let filteredCaseIds = D.cases.map(c => c.case_id);
let activeView = 'overview';

/* ── Helpers ───────────────────────────────────────────────────────────── */
const $ = id => document.getElementById(id);

function esc(s) {
  return String(s ?? '—')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function decisionBadge(d) {
  const cls = (d || '').toLowerCase();
  if (!cls) return '<span class="badge ok">—</span>';
  return `<span class="badge ${cls}">${esc(d)}</span>`;
}

function sevBadge(s) {
  const cls = (s || 'low').toLowerCase();
  return `<span class="badge ${cls}">${esc(s)}</span>`;
}

function pct(v) {
  return typeof v === 'number' ? Math.round(v * 100) + '%' : '—';
}

function getCaseById(id) { return D.cases.find(c => c.case_id === id) || null; }
function getRulesById(id) { return D.ruleResults[id] || []; }
function getDiagById(id) { return D.diagnoses[id] || null; }
function getReviewById(id) { return D.reviewLog.find(r => r.case_id === id) || null; }

/* build review decision lookup once */
function buildReviewMap() {
  const m = {};
  D.reviewLog.forEach(r => { m[r.case_id] = r.decision; });
  return m;
}

let isHistoryLoaded = false;

/* ── Navigation ─────────────────────────────────────────────────────────── */
function showView(name) {
  if (activeView === name && name !== 'explorer') return;   // skip re-render except explorer
  activeView = name;

  /* hide all views */
  document.querySelectorAll('.view').forEach(v => v.classList.remove('active'));

  /* deactivate all nav items (sidebar + mobile) */
  document.querySelectorAll('.nav-item, .mobile-nav-btn').forEach(n => n.classList.remove('active'));

  /* activate the target view */
  const v = $(`view-${name}`);
  if (v) {
    v.classList.add('active');
    v.scrollTop = 0;          /* reset scroll position */
  }

  /* activate the matching nav buttons */
  const sideNav = $(`nav-${name}`);
  if (sideNav) sideNav.classList.add('active');
  const mobileNav = $(`m-nav-${name}`);
  if (mobileNav) mobileNav.classList.add('active');

  /* Resize charts when switching to overview */
  if (name === 'overview') {
    requestAnimationFrame(resizeCharts);
  } else if (name === 'history') {
    if (!isHistoryLoaded) {
      loadHistory();
      isHistoryLoaded = true;
    }
  } else if (name === 'diagnose') {
    if (!currentLiveCaseId && typeof startNewLiveSession === 'function') {
      startNewLiveSession();
      loadLiveCasesDropdown();
    }
  }
}

/* Quick demo: navigate to Case Explorer and select C-001 */
function loadDemo() {
  showView('explorer');
  selectCase('C-001');
  setTimeout(() => {
    const el = document.querySelector('.case-item.active');
    if (el) el.scrollIntoView({ block: 'nearest' });
  }, 80);
}

/* ── Tab switching ──────────────────────────────────────────────────────── */
function showTab(name) {
  document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
  document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
  const btn = $(`tab-${name}`);
  const content = $(`content-${name}`);
  if (btn) btn.classList.add('active');
  if (content) content.classList.add('active');
}

/* ══════════════════════════════════════════════════════════════════════════
   VIEW 1 — OVERVIEW
══════════════════════════════════════════════════════════════════════════ */
function renderOverview() {
  const dash = D.dashboard;
  const accepted = dash.review_decisions?.Accepted ?? 0;
  const edited = dash.review_decisions?.Edited ?? 0;
  const rejected = dash.review_decisions?.Rejected ?? 0;

  /* Metric cards */
  $('metric-grid').innerHTML = `
    <div class="metric-card">
      <div class="metric-label">Total Cases</div>
      <div class="metric-value accent">${dash.total_cases}</div>
      <div class="metric-sub">Labelled fault scenarios</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">AI Accepted</div>
      <div class="metric-value green">${accepted}</div>
      <div class="metric-sub">No correction needed</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Edited</div>
      <div class="metric-value amber">${edited}</div>
      <div class="metric-sub">Reviewer corrected fields</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Rejected</div>
      <div class="metric-value red">${rejected}</div>
      <div class="metric-sub">Diagnosis substantially wrong</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Agreement Rate</div>
      <div class="metric-value accent">${pct(dash.agreement_rate)}</div>
      <div class="metric-sub">AI accepted without edit</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Correction Rate</div>
      <div class="metric-value amber">${pct(dash.correction_rate)}</div>
      <div class="metric-sub">Required human correction</div>
    </div>`;

  /* Charts */
  renderBarChart('chart-categories', dash.issue_type_distribution,
    ['#4f7ef8', '#6588f9', '#7c9ffc', '#93b1fd', '#a8c3fe', '#bcd4ff', '#cde2ff', '#deedff']);
  renderPieChart('chart-decisions', dash.review_decisions,
    ['#4ade80', '#fbbf24', '#f87171']);
  renderBarChart('chart-severity', dash.severity_distribution,
    ['#f87171', '#fbbf24', '#4ade80']);

  /* Rule count table */
  const rc = dash.rule_finding_counts || {};
  const ruleRows = Object.entries(rc)
    .sort((a, b) => b[1] - a[1])
    .map(([name, count]) => `
      <tr>
        <td>${esc(name)}</td>
        <td>${count > 0
        ? `<span class="badge triggered">⚠ ${count} triggered</span>`
        : `<span class="badge ok">✓ 0</span>`}</td>
        <td>${count > 0 ? `Triggered in ${count} of ${dash.total_cases} cases` : 'Not triggered in any case'}</td>
      </tr>`).join('');
  $('rule-count-table').innerHTML = `
    <thead><tr><th>Rule function</th><th>Count</th><th>Note</th></tr></thead>
    <tbody>${ruleRows || '<tr><td colspan="3" style="color:var(--text-muted)">No rule data available.</td></tr>'}</tbody>`;
}

/* ── SVG bar chart with ResizeObserver ──────────────────────────────────── */
const _chartRegistry = {};  // svgId → { data, colours, type }

function renderBarChart(svgId, data, colours) {
  _chartRegistry[svgId] = { data, colours, type: 'bar' };
  _doRenderBar(svgId, data, colours);
}

function _doRenderBar(svgId, data, colours) {
  const svg = $(svgId);
  if (!svg || !data) return;
  const entries = Object.entries(data);
  if (!entries.length) return;

  const parent = svg.parentElement;
  const W = (parent ? parent.clientWidth - 36 : 0) || 340;
  const H = parseInt(svg.getAttribute('height')) || 200;
  const padL = 8, padR = 8, padT = 18, padB = 36;
  const innerW = W - padL - padR;
  const innerH = H - padT - padB;
  const maxVal = Math.max(...entries.map(e => e[1])) || 1;
  const gap = 4;
  const barW = Math.max(Math.floor(innerW / entries.length) - gap, 6);

  const bars = entries.map(([label, val], i) => {
    const bH = Math.max(Math.round((val / maxVal) * innerH), val > 0 ? 2 : 0);
    const x = padL + i * (barW + gap);
    const y = padT + innerH - bH;
    const col = colours[i % colours.length];
    const truncLabel = label.length > 10 ? label.slice(0, 9) + '…' : label;
    return `
      <rect x="${x}" y="${y}" width="${barW}" height="${bH}" rx="3" fill="${col}" opacity="0.9"/>
      <text x="${x + barW / 2}" y="${y - 4}" text-anchor="middle" class="bar-value">${val}</text>
      <text x="${x + barW / 2}" y="${H - padB + 14}" text-anchor="middle" class="bar-label">${esc(truncLabel)}</text>`;
  }).join('');

  svg.setAttribute('viewBox', `0 0 ${W} ${H}`);
  svg.innerHTML = bars;
}

/* ── SVG pie chart ──────────────────────────────────────────────────────── */
function renderPieChart(svgId, data, colours) {
  _chartRegistry[svgId] = { data, colours, type: 'pie' };
  _doRenderPie(svgId, data, colours);
}

function _doRenderPie(svgId, data, colours) {
  const svg = $(svgId);
  if (!svg || !data) return;
  const entries = Object.entries(data);
  const total = entries.reduce((s, e) => s + e[1], 0);
  if (!total) return;

  const parent = svg.parentElement;
  const W = (parent ? parent.clientWidth - 36 : 0) || 300;
  const H = parseInt(svg.getAttribute('height')) || 200;
  const cx = W * 0.36, cy = H / 2, r = Math.min(cx, cy) - 16;

  let paths = '', legendItems = '';
  let angle = -Math.PI / 2;

  entries.forEach(([label, val], i) => {
    const slice = (val / total) * 2 * Math.PI;
    const x1 = cx + r * Math.cos(angle);
    const y1 = cy + r * Math.sin(angle);
    const x2 = cx + r * Math.cos(angle + slice);
    const y2 = cy + r * Math.sin(angle + slice);
    const large = slice > Math.PI ? 1 : 0;
    const col = colours[i % colours.length];
    paths += `<path d="M${cx},${cy} L${x1},${y1} A${r},${r} 0 ${large},1 ${x2},${y2} Z"
              fill="${col}" opacity="0.9" stroke="var(--bg-base)" stroke-width="1.5"/>`;
    const legendY = 28 + i * 26;
    legendItems += `
      <rect x="${W * 0.70}" y="${legendY - 8}" width="10" height="10" rx="2" fill="${col}" opacity="0.9"/>
      <text x="${W * 0.70 + 15}" y="${legendY}" class="pie-label">
        ${esc(label)}: ${val} (${Math.round(val / total * 100)}%)
      </text>`;
    angle += slice;
  });

  svg.setAttribute('viewBox', `0 0 ${W} ${H}`);
  svg.innerHTML = paths + legendItems;
}

/* Re-render all registered charts (called on resize / view switch) */
function resizeCharts() {
  Object.entries(_chartRegistry).forEach(([id, { data, colours, type }]) => {
    if (type === 'bar') _doRenderBar(id, data, colours);
    else _doRenderPie(id, data, colours);
  });
}

/* ══════════════════════════════════════════════════════════════════════════
   VIEW 2 — CASE EXPLORER
══════════════════════════════════════════════════════════════════════════ */
function renderCaseList() {
  /* Populate category dropdown */
  const cats = [...new Set(D.cases.map(c => c.category))].sort();
  $('filter-category').innerHTML = '<option value="">All Categories</option>' +
    cats.map(c => `<option value="${esc(c)}">${esc(c)}</option>`).join('');

  /* Populate severity dropdown */
  const sevs = [...new Set(D.cases.map(c => c.severity).filter(Boolean))].sort();
  $('filter-severity').innerHTML = '<option value="">All Severities</option>' +
    sevs.map(s => `<option value="${esc(s)}">${esc(s)}</option>`).join('');

  filterCases();
}

function filterCases() {
  const q = ($('case-search').value || '').toLowerCase().trim();
  const cat = $('filter-category').value;
  const dec = $('filter-decision').value;
  const sev = $('filter-severity').value;

  const reviewMap = buildReviewMap();

  filteredCaseIds = D.cases
    .filter(c => {
      if (cat && c.category !== cat) return false;
      if (sev && c.severity !== sev) return false;
      if (dec && reviewMap[c.case_id] !== dec) return false;
      if (q) {
        const hay = [c.case_id, c.title, c.category, c.symptom, c.concept, c.severity,
        c.topology_note, c.expected_fault]
          .join(' ').toLowerCase();
        if (!hay.includes(q)) return false;
      }
      return true;
    })
    .map(c => c.case_id);

  $('case-count').textContent = `${filteredCaseIds.length} of ${D.cases.length} cases`;

  const list = $('case-list');
  if (!filteredCaseIds.length) {
    list.innerHTML = `<div class="no-results">No cases match your filters.</div>`;
    return;
  }

  list.innerHTML = filteredCaseIds.map(id => {
    const c = getCaseById(id);
    const decision = reviewMap[id] || '';
    const decClass = decision.toLowerCase();
    const isActive = id === selectedCaseId ? 'active' : '';
    return `
      <div class="case-item ${isActive}" id="ci-${id}"
           onclick="selectCase('${id}')" role="button" tabindex="0"
           onkeydown="if(event.key==='Enter')selectCase('${id}')">
        <span class="case-id">${esc(id)}</span>
        <div class="case-info">
          <div class="case-title-sm">${esc(c.title)}</div>
          <div class="case-cat">${esc(c.category)} · ${esc(c.severity)}</div>
        </div>
        ${decision ? `<span class="badge ${decClass}" style="font-size:9px;padding:2px 6px">${esc(decision)}</span>` : ''}
      </div>`;
  }).join('');
}

function selectCase(id) {
  /* Safety: clear old state to prevent stale data leak */
  const prev = selectedCaseId;
  selectedCaseId = id;

  /* Update list highlight — handle both list panels */
  document.querySelectorAll('.case-item').forEach(el => el.classList.remove('active'));
  const item = $(`ci-${id}`);
  if (item) item.classList.add('active');

  /* Show tab panel, hide empty state */
  const emptyState = $('empty-state');
  const caseTabs = $('case-tabs');
  if (emptyState) emptyState.style.display = 'none';
  if (caseTabs) caseTabs.style.display = '';

  const c = getCaseById(id);
  const rules = getRulesById(id);
  const diag = getDiagById(id);
  const review = getReviewById(id);

  if (!c) {
    if (emptyState) emptyState.style.display = '';
    if (caseTabs) caseTabs.style.display = 'none';
    return;
  }

  renderCaseInfo(c, review);
  renderEvidence(c);
  renderRuleFindings(rules);
  renderDiagnosis(diag, id);
  renderReviewTab(review);

  showTab('info');

  /* Update "selected case" banner if on Human Review page */
  updateReviewSelectedBanner();
}

/* ── Tab: Case Info ──────────────────────────────────────────────────────── */
function renderCaseInfo(c, review) {
  const decision = review?.decision || '';
  $('info-grid').innerHTML = `
    <div class="info-field">
      <div class="field-label">Case ID</div>
      <div class="field-value" style="font-family:'JetBrains Mono',monospace;font-size:15px;font-weight:700;color:var(--accent)">${esc(c.case_id)}</div>
    </div>
    <div class="info-field">
      <div class="field-label">Review Decision</div>
      <div class="field-value">${decisionBadge(decision)}</div>
    </div>
    <div class="info-field full">
      <div class="field-label">Title</div>
      <div class="field-value" style="font-weight:600;font-size:13px">${esc(c.title)}</div>
    </div>
    <div class="info-field">
      <div class="field-label">Category</div>
      <div class="field-value">${esc(c.category)}</div>
    </div>
    <div class="info-field">
      <div class="field-label">Severity</div>
      <div class="field-value">${sevBadge(c.severity)}</div>
    </div>
    <div class="info-field">
      <div class="field-label">OSI Layer</div>
      <div class="field-value">Layer ${esc(c.osi_layer)}</div>
    </div>
    <div class="info-field">
      <div class="field-label">Concept</div>
      <div class="field-value">${esc(c.concept)}</div>
    </div>
    <div class="info-field full">
      <div class="field-label">Symptom Observed</div>
      <div class="info-box">${esc(c.symptom)}</div>
    </div>
    <div class="info-field full">
      <div class="field-label">Topology Note</div>
      <div class="field-value">${esc(c.topology_note)}</div>
    </div>
    <div class="info-field full">
      <div class="field-label">Expected Fault (Ground Truth)</div>
      <div class="info-box fault-border">${esc(c.expected_fault)}</div>
    </div>
    <div class="info-field">
      <div class="field-label">Expected Next Command</div>
      <div class="field-value" style="font-family:'JetBrains Mono',monospace;font-size:11px;color:var(--text-code)">${esc(c.expected_next_command)}</div>
    </div>
    <div class="info-field">
      <div class="field-label">Expected Fix</div>
      <div class="field-value" style="font-family:'JetBrains Mono',monospace;font-size:11px;color:var(--text-code)">${esc(c.expected_fix)}</div>
    </div>`;
}

/* ── Tab: Evidence ───────────────────────────────────────────────────────── */
function renderEvidence(c) {
  const block = $('evidence-block');
  if (!c.show_outputs || c.show_outputs.trim() === '') {
    block.textContent = '(No show-command output recorded for this case)';
    return;
  }
  block.textContent = c.show_outputs;
}

/* ── Tab: Rule Findings ──────────────────────────────────────────────────── */
function renderRuleFindings(rules) {
  const tbody = $('rule-findings-body');
  if (!rules || !rules.length) {
    tbody.innerHTML = `<tr><td colspan="3" style="color:var(--text-muted);padding:14px 10px">
      No rule results available for this case.</td></tr>`;
    return;
  }
  tbody.innerHTML = rules.map(r => {
    const badge = r.triggered
      ? '<span class="badge triggered">⚠ Triggered</span>'
      : '<span class="badge ok">✓ Not triggered</span>';
    const detail = (r.detail && r.detail.trim() && r.detail !== 'null')
      ? esc(r.detail)
      : (r.triggered ? 'Rule condition met' : 'Rule condition not met');
    return `
      <tr>
        <td>${esc(r.rule_name)}</td>
        <td style="white-space:nowrap">${badge}</td>
        <td>${detail}</td>
      </tr>`;
  }).join('');
}

/* ── Tab: AI Diagnosis ───────────────────────────────────────────────────── */
function renderDiagnosis(diag, caseId) {
  const el = $('diagnosis-content');

  if (!diag) {
    el.innerHTML = `<div class="empty-state">
      <div class="empty-icon">🤖</div>
      <h3>No diagnosis data</h3>
      <p>No entry found in <code>diagnoses.json</code> for ${esc(caseId)}.</p>
    </div>`;
    return;
  }

  if (diag.status === 'needs_manual_review') {
    el.innerHTML = `
      <div class="review-card" style="border-color:var(--edited-border)">
        <div class="field-label" style="color:var(--edited-text);margin-bottom:8px">
          ⚠ Status: needs_manual_review
        </div>
        <p class="field-value" style="margin-bottom:10px">
          Both Gemini API attempts returned invalid JSON.
          Raw response is preserved below for human review.
        </p>
        <pre class="evidence-block">${esc(diag.raw_response || '(empty)')}</pre>
      </div>`;
    return;
  }

  const pd = diag.parsed_diagnosis || {};
  const conf = typeof pd.confidence === 'number' ? pd.confidence : 0;
  const confPct = Math.round(conf * 100);
  const confCol = confPct >= 70 ? 'var(--accepted-text)' : confPct >= 40 ? 'var(--edited-text)' : 'var(--rejected-text)';

  const evidenceList = Array.isArray(pd.evidence)
    ? pd.evidence.map(e => `<li>${esc(e)}</li>`).join('')
    : `<li>${esc(pd.evidence)}</li>`;

  const fixList = Array.isArray(pd.fix_steps)
    ? pd.fix_steps.map((s, i) => `<li><strong style="color:var(--accent)">${i + 1}.</strong> ${esc(s)}</li>`).join('')
    : `<li>${esc(pd.fix_steps)}</li>`;

  el.innerHTML = `
    <div>
      <div class="field-label">Root Cause</div>
      <div class="diag-root-cause" style="margin-top:6px">${esc(pd.root_cause)}</div>
    </div>

    <div class="info-grid">
      <div class="info-field">
        <div class="field-label">Confidence</div>
        <div class="field-value" style="color:${confCol};font-weight:700;font-size:22px;margin-top:2px">${confPct}%</div>
        <div class="confidence-bar">
          <div class="confidence-fill" style="width:${confPct}%;background:${confCol}"></div>
        </div>
      </div>
      <div class="info-field">
        <div class="field-label">OSI Layer</div>
        <div class="field-value" style="margin-top:4px">${esc(pd.osi_layer)}</div>
      </div>
    </div>

    <div>
      <div class="field-label" style="margin-bottom:8px">Supporting Evidence (from AI)</div>
      <ul class="list-plain">${evidenceList || '<li style="color:var(--text-muted)">No evidence listed.</li>'}</ul>
    </div>

    <div>
      <div class="field-label">Recommended Next Command</div>
      <pre class="evidence-block" style="max-height:80px;margin-top:6px">${esc(pd.next_command || '—')}</pre>
    </div>

    <div>
      <div class="field-label" style="margin-bottom:8px">Fix Steps</div>
      <ul class="list-plain">${fixList || '<li style="color:var(--text-muted)">No fix steps listed.</li>'}</ul>
    </div>

    <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:2px">
      <span class="meta-pill">prompt: ${esc(diag.prompt_version)}</span>
      <span class="meta-pill">model: ${esc(diag.model)}</span>
    </div>`;
}

/* ── Tab: Human Review ───────────────────────────────────────────────────── */
function renderReviewTab(review) {
  const el = $('review-content');

  if (!review) {
    el.innerHTML = `<div class="empty-state">
      <div class="empty-icon">👤</div>
      <h3>No review record</h3>
      <p>No human review entry is available for this case in <code>review_log.csv</code>.</p>
    </div>`;
    return;
  }

  const dec = review.decision || '';
  const decLower = dec.toLowerCase();
  const corr = review.corrected_fields?.trim() || null;

  const corrPills = corr
    ? corr.split(',').map(f =>
      `<span class="meta-pill" style="color:var(--edited-text)">${esc(f.trim())}</span>`
    ).join('')
    : null;

  el.innerHTML = `
    <div class="review-card">
      <div class="review-header">
        <div>
          <div class="field-label">Human Review Decision</div>
          <div style="margin-top:7px">${decisionBadge(dec)}</div>
        </div>
        <div style="text-align:right">
          <div class="field-label">Reviewer</div>
          <div class="field-value" style="margin-top:4px">${esc(review.reviewer)}</div>
        </div>
      </div>

      ${corrPills ? `
      <div style="margin-bottom:14px">
        <div class="field-label">Corrected Fields</div>
        <div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:7px">${corrPills}</div>
      </div>` : ''}

      <div>
        <div class="field-label">Reviewer Reason</div>
        <div class="info-box" style="margin-top:6px">
          ${review.reason?.trim()
      ? esc(review.reason)
      : '<em style="color:var(--text-muted)">No reason recorded (case accepted without comment).</em>'}
        </div>
      </div>
    </div>

    <div class="section-block">
      <div class="section-title">What this means</div>
      ${decLower === 'accepted'
      ? '<p style="font-size:12px;color:var(--text-secondary)">The AI diagnosis was reviewed and accepted as-is. No field corrections were required.</p>'
      : ''}
      ${decLower === 'edited'
      ? `<p style="font-size:12px;color:var(--text-secondary)">The reviewer found the AI diagnosis partially correct but requiring field-level corrections. The fields listed above were manually corrected. This demonstrates human oversight — the AI output was not blindly trusted.</p>`
      : ''}
      ${decLower === 'rejected'
      ? `<p style="font-size:12px;color:var(--rejected-text)">The AI diagnosis was substantially wrong and was rejected entirely. A correct diagnosis was recorded in <code>docs/responsible_ai_log.md</code>. This is an important responsible-AI data point.</p>`
      : ''}
    </div>`;
}

/* ══════════════════════════════════════════════════════════════════════════
   VIEW 3 — HUMAN REVIEW (full table)
══════════════════════════════════════════════════════════════════════════ */
function renderHumanReview() {
  const dash = D.dashboard;
  const dec = dash.review_decisions || {};

  /* Summary metrics */
  $('review-summary-cards').innerHTML = `
    <div class="metric-card">
      <div class="metric-label">Accepted</div>
      <div class="metric-value green">${dec.Accepted ?? 0}</div>
      <div class="metric-sub">AI diagnosis correct</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Edited</div>
      <div class="metric-value amber">${dec.Edited ?? 0}</div>
      <div class="metric-sub">Fields corrected</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Rejected</div>
      <div class="metric-value red">${dec.Rejected ?? 0}</div>
      <div class="metric-sub">Diagnosis wrong</div>
    </div>`;

  const caseMap = {};
  D.cases.forEach(c => { caseMap[c.case_id] = c; });

  const tbody = $('all-review-body');
  tbody.innerHTML = D.reviewLog.map(r => {
    const c = caseMap[r.case_id] || {};
    const dec = r.decision || '';
    return `
      <tr onclick="openCaseInExplorer('${r.case_id}')" style="cursor:pointer" tabindex="0"
          onkeydown="if(event.key==='Enter')openCaseInExplorer('${r.case_id}')">
        <td class="mono">${esc(r.case_id)}</td>
        <td>${esc(c.category || '—')}</td>
        <td>${decisionBadge(dec)}</td>
        <td style="font-family:'JetBrains Mono',monospace;font-size:10px;color:var(--text-code)">
          ${r.corrected_fields ? esc(r.corrected_fields) : '<span style="color:var(--text-muted)">—</span>'}
        </td>
        <td>${esc(r.reviewer)}</td>
      </tr>`;
  }).join('');
}

function openCaseInExplorer(id) {
  showView('explorer');
  selectCase(id);
  setTimeout(() => {
    const el = $(`ci-${id}`);
    if (el) el.scrollIntoView({ block: 'nearest' });
  }, 80);
}

/* Banner in Human Review page showing selected case (if any) */
function updateReviewSelectedBanner() {
  const banner = $('review-selected-banner');
  if (!banner) return;
  if (!selectedCaseId) {
    banner.style.display = 'none';
    return;
  }
  const review = getReviewById(selectedCaseId);
  if (!review) {
    banner.style.display = 'none';
    return;
  }
  banner.style.display = '';
  banner.innerHTML = `
    <span style="font-size:11px;color:var(--text-muted)">Currently viewing:</span>
    <span style="font-family:'JetBrains Mono',monospace;font-size:12px;font-weight:700;color:var(--accent)">${esc(selectedCaseId)}</span>
    ${decisionBadge(review.decision)}
    <button onclick="openCaseInExplorer('${selectedCaseId}')"
            style="margin-left:auto;border:1px solid var(--accent-glow);background:var(--accent-dim);color:var(--accent);
                   border-radius:20px;padding:3px 10px;font-size:11px;cursor:pointer;font-family:'Inter',sans-serif">
      Open in Explorer →
    </button>`;
}

/* ══════════════════════════════════════════════════════════════════════════
   VIEW 4 — RESPONSIBLE AI
══════════════════════════════════════════════════════════════════════════ */
function renderResponsibleAI() {
  const interventions = D.reviewLog.filter(r => r.decision === 'Edited' || r.decision === 'Rejected');
  const accepted = D.reviewLog.filter(r => r.decision === 'Accepted').length;
  const total = D.reviewLog.length;

  $('rai-total').textContent = interventions.length;
  $('rai-accepted').textContent = accepted;
  $('rai-rate').textContent = total ? Math.round((interventions.length / total) * 100) + '%' : '—';

  const caseMap = {};
  D.cases.forEach(c => { caseMap[c.case_id] = c; });

  const tbody = $('rai-body');
  if (!interventions.length) {
    tbody.innerHTML = `<tr><td colspan="6" style="padding:18px;text-align:center;color:var(--text-muted)">
      All AI diagnoses were accepted without correction.</td></tr>`;
    return;
  }

  tbody.innerHTML = interventions.map(r => {
    const c = caseMap[r.case_id] || {};
    const diag = D.diagnoses[r.case_id];
    const aiRoot = diag?.parsed_diagnosis?.root_cause
      ? diag.parsed_diagnosis.root_cause.slice(0, 110) +
      (diag.parsed_diagnosis.root_cause.length > 110 ? '…' : '')
      : (diag?.status === 'needs_manual_review' ? '(needs_manual_review)' : '—');
    const corr = r.corrected_fields
      ? r.corrected_fields.split(',')
        .map(f => `<span class="meta-pill" style="color:var(--edited-text);margin:2px">${esc(f.trim())}</span>`)
        .join('')
      : '<span style="color:var(--text-muted)">—</span>';

    return `
      <tr onclick="openCaseInExplorer('${r.case_id}')" style="cursor:pointer" tabindex="0"
          onkeydown="if(event.key==='Enter')openCaseInExplorer('${r.case_id}')">
        <td class="mono">${esc(r.case_id)}</td>
        <td>${esc(c.category || '—')}</td>
        <td style="white-space:nowrap">${decisionBadge(r.decision)}</td>
        <td style="font-size:11px;color:var(--text-secondary)">${esc(aiRoot)}</td>
        <td style="white-space:nowrap">${corr}</td>
        <td style="font-size:11px;color:var(--text-secondary)">${esc(r.reason || '—')}</td>
      </tr>`;
  }).join('');
}

/* ══════════════════════════════════════════════════════════════════════════
   VIEW 5 — WORKFLOW
══════════════════════════════════════════════════════════════════════════ */
const WORKFLOW_STEPS = [
  {
    num_type: 'ext',
    tags: [{ cls: 'ext', label: 'External Environment' }],
    title: 'Cisco Packet Tracer Lab',
    desc: 'The engineer works in a Cisco Packet Tracer simulation. They observe a network fault — for example, a PC cannot reach its gateway, or a ping fails between subnets. NetSage-AI does not directly control Packet Tracer.',
  },
  {
    num_type: 'human',
    tags: [{ cls: 'human', label: 'Manual — Engineer' }],
    title: 'Collect Evidence',
    desc: 'The engineer runs Cisco show commands (show vlan brief, show ip interface brief, show ip route, etc.) and records the symptom, topology note, and full CLI output as a case row in data/cases.csv.',
  },
  {
    num_type: '',
    tags: [{ cls: 'auto', label: 'Automated' }],
    title: 'Deterministic Rule Checking',
    desc: 'scripts/rule_checker.py runs six regex-based checks on the show-command text: duplicate IP, wrong subnet mask, gateway mismatch, interface down, missing VLAN assignment, missing route. Each returns a Finding (triggered: true/false, detail).',
  },
  {
    num_type: '',
    tags: [{ cls: 'auto', label: 'Automated' }],
    title: 'AI Diagnosis — Google Gemini',
    desc: 'scripts/diagnose.py assembles a structured prompt (symptom + topology + evidence + rule findings) and calls the Gemini API (gemini-3.5-flash-lite, temperature=0.0, AFC disabled). The model returns a JSON diagnosis object.',
  },
  {
    num_type: '',
    tags: [{ cls: 'auto', label: 'Automated' }],
    title: 'JSON Schema Validation',
    desc: 'scripts/validate_diagnosis.py validates the response against a strict 6-field schema using jsonschema (root_cause, confidence, osi_layer, evidence, next_command, fix_steps). If invalid, one retry is attempted. If both fail: status = needs_manual_review.',
  },
  {
    num_type: 'human',
    tags: [{ cls: 'human', label: 'Human — Reviewer' }],
    title: 'Human Review',
    desc: 'A human expert reviews every AI diagnosis and records Accept / Edit / Reject in data/review_log.csv, along with corrected fields and a reason. Cases with substantial errors are documented in docs/responsible_ai_log.md.',
  },
  {
    num_type: '',
    tags: [{ cls: 'auto', label: 'Automated' }],
    title: 'Dashboard & Metrics',
    desc: 'scripts/build_dashboard.py aggregates all review results and generates agreement_rate, correction_rate, and issue-type distribution charts. This presentation UI loads those metrics from dashboard/dashboard_data.json via build_data_bridge.py.',
  },
  {
    num_type: 'ext',
    tags: [{ cls: 'ext', label: 'External Environment' }],
    title: 'Engineer Applies & Verifies Fix in Packet Tracer',
    desc: 'The engineer takes the recommended fix commands (from fix_steps) back to the Cisco Packet Tracer lab and applies them. They verify the fault is resolved (e.g., ping now succeeds). NetSage does not directly control Packet Tracer — it advises; the engineer acts.',
  },
];

function renderWorkflow() {
  const container = $('workflow-steps');
  container.innerHTML = WORKFLOW_STEPS.map((step, i) => {
    const numClass = step.num_type ? ` ${step.num_type}` : '';
    const tags = step.tags.map(t => `<span class="wf-tag ${t.cls}">${t.label}</span>`).join('');
    const connector = i < WORKFLOW_STEPS.length - 1 ? '<div class="wf-connector"></div>' : '';
    return `
      <div class="wf-step">
        <div class="wf-left">
          <div class="wf-num${numClass}">${i + 1}</div>
          ${connector}
        </div>
        <div class="wf-body">
          <div class="wf-body-tags">${tags}</div>
          <div class="wf-title">${esc(step.title)}</div>
          <div class="wf-desc">${esc(step.desc)}</div>
        </div>
      </div>`;
  }).join('');
}

/* ══════════════════════════════════════════════════════════════════════════
   VIEW 6 — LIVE DIAGNOSIS
══════════════════════════════════════════════════════════════════════════ */

let currentLiveCaseId = null;
let currentDiagnosisRecord = null;
let currentReviewDecision = null;

function loadLiveCasesDropdown() {
  const sel = $('diag-case-select');
  if (!sel) return;
  const opts = D.cases.map(c => `<option value="${c.case_id}">${c.case_id} - ${c.title}</option>`);
  sel.innerHTML += opts.join('');
}

function loadSelectedLiveCase() {
  const caseId = $('diag-case-select').value;
  if (!caseId) {
    startNewLiveSession();
    return;
  }
  const c = getCaseById(caseId);
  if (c) {
    currentLiveCaseId = `LIVE-${c.case_id}-${Math.floor(Math.random() * 10000).toString().padStart(4, '0')}`;
    clearLiveForm();
    $('diag-case-select').value = caseId;
    $('diag-symptom').value = c.symptom || '';
    $('diag-topology').value = c.topology_note || '';
    $('diag-show-outputs').value = c.show_outputs || '';
  }
}

function updateStepBadge(step, isActive) {
  const b = $(`step-${step}`);
  if (!b) return;
  if (isActive) {
    b.className = 'badge';
    b.style.background = 'var(--accent)';
    b.style.color = 'white';
  } else {
    b.className = 'badge ok';
    b.style.background = 'var(--bg-base)';
    b.style.color = 'var(--text-muted)';
  }
}

function clearLiveForm() {
  $('diag-case-select').value = '';
  $('diag-symptom').value = '';
  $('diag-topology').value = '';
  $('diag-show-outputs').value = '';

  $('live-rule-area').style.display = 'none';
  $('live-validation-area').style.display = 'none';
  $('live-result-area').style.display = 'none';
  $('live-review-area').style.display = 'none';
  $('live-verification-area').style.display = 'none';
  $('live-complete-area').style.display = 'none';
  $('live-error-area').style.display = 'none';

  $('run-diagnose-btn').disabled = true;
  currentDiagnosisRecord = null;
  currentReviewDecision = null;

  const el = $('live-session-id');
  if (el) el.textContent = currentLiveCaseId ? `Active Session: ${currentLiveCaseId}` : '';

  for (let i = 2; i <= 6; i++) updateStepBadge(i, false);
}

function startNewLiveSession() {
  const dateStr = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);
  const randomSuffix = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
  currentLiveCaseId = `LIVE-${dateStr}-${randomSuffix}`;
  clearLiveForm();
}

async function runLiveRuleCheck() {
  const showOutputs = $('diag-show-outputs').value.trim();
  if (!showOutputs) {
    showLiveError('Please provide Show-Command Outputs.');
    return;
  }

  const btn = $('run-rule-btn');
  const txt = $('rule-btn-text');
  const sp = $('rule-spinner');
  btn.disabled = true; txt.textContent = 'Checking...'; sp.style.display = '';
  $('live-error-area').style.display = 'none';

  try {
    const res = await fetch('/api/rules', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ show_outputs: showOutputs })
    });
    if (!res.ok) throw new Error(`API returned ${res.status}`);
    const findings = await res.json();

    // Render findings
    $('live-rule-tbody').innerHTML = findings.map(f => {
      const badge = f.triggered ? '<span class="badge triggered">⚠ Triggered</span>' : '<span class="badge ok">✓ Not triggered</span>';
      return `<tr><td>${esc(f.rule_name)}</td><td>${badge}</td><td>${esc(f.detail)}</td></tr>`;
    }).join('');

    $('live-rule-area').style.display = '';
    $('run-diagnose-btn').disabled = false;
    updateStepBadge(2, true);

  } catch (err) {
    showLiveError("Failed to fetch rule check: Make sure local_server.py is running!");
  } finally {
    btn.disabled = false; txt.textContent = '🔍 Run Rule Check'; sp.style.display = 'none';
  }
}

async function runLiveDiagnosis() {
  $('live-error-area').style.display = 'none';
  $('live-validation-area').style.display = 'none';
  $('live-result-area').style.display = 'none';
  $('live-review-area').style.display = 'none';

  const symptom = $('diag-symptom').value.trim();
  const topology = $('diag-topology').value.trim();
  const showOutputs = $('diag-show-outputs').value.trim();

  const btn = $('run-diagnose-btn');
  const txt = $('diagnose-btn-text');
  const sp = $('diagnose-spinner');
  btn.disabled = true; txt.textContent = 'Diagnosing...'; sp.style.display = '';

  try {
    const res = await fetch('/api/diagnose', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ session_id: currentLiveCaseId, symptom, topology, show_outputs: showOutputs })
    });

    if (!res.ok) {
      const errBody = await res.json();
      throw new Error(errBody.message || `API error ${res.status}`);
    }

    const data = await res.json();
    currentDiagnosisRecord = data;
    updateStepBadge(3, true);
    updateStepBadge(4, true);

    if (data.status === 'needs_manual_review') {
      $('live-fallback-json').textContent = data.raw_response;
      $('live-validation-area').style.display = '';
    } else {
      renderLiveResult(data.parsed_diagnosis, data.raw_response);
      $('live-review-area').style.display = '';
      $('review-extra').style.display = 'none';
      $('review-reason').value = '';
      $('review-status').style.display = 'none';
    }
  } catch (err) {
    showLiveError(err.message || 'Diagnosis failed. Check backend logs and GEMINI_API_KEY config in .env.');
  } finally {
    btn.disabled = false; txt.textContent = '⚡ Run AI Diagnosis'; sp.style.display = 'none';
  }
}

function showLiveError(msg) {
  $('live-error-area').style.display = '';
  $('live-error-msg').textContent = msg;
}

function submitReviewAction(decision) {
  currentReviewDecision = decision;

  const editForm = $('edit-diagnosis-form');
  if (editForm) {
    if (decision === 'Edited') {
      editForm.style.display = 'block';
      const pd = currentDiagnosisRecord?.parsed_diagnosis || {};
      $('edit-root-cause').value = pd.root_cause || '';
      $('edit-osi-layer').value = pd.osi_layer || '';
      $('edit-next-command').value = pd.next_command || '';
      let fixes = pd.fix_steps;
      if (Array.isArray(fixes)) fixes = fixes.join('\n');
      $('edit-fix-steps').value = (fixes || '');
    } else {
      editForm.style.display = 'none';
    }
  }

  if (decision === 'Accepted') {
    $('review-extra').style.display = 'block';
    $('review-reason').value = 'Automated Acceptance via UI Action';
  } else {
    $('review-extra').style.display = 'block';
    $('review-reason').value = '';
    $('review-reason').focus();
  }
}

function submitReviewActionFinal() {
  finalizeReview();
}

async function finalizeReview() {
  const reason = $('review-reason').value.trim();
  if ((currentReviewDecision === 'Edited' || currentReviewDecision === 'Rejected') && !reason) {
    alert("Please provide a reason for editing or rejecting the diagnosis.");
    return;
  }

  const payload = {
    session_id: currentLiveCaseId,
    decision: currentReviewDecision,
    reason: reason
  };

  if (currentReviewDecision === 'Edited') {
    const fixesStr = $('edit-fix-steps').value;
    payload.edited_diagnosis = {
      root_cause: $('edit-root-cause').value.trim(),
      osi_layer: $('edit-osi-layer').value.trim(),
      next_command: $('edit-next-command').value.trim(),
      fix_steps: fixesStr.split('\n').map(s => s.trim()).filter(Boolean)
    };
  }

  try {
    const res = await fetch('/api/review', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
    if (!res.ok) throw new Error("Could not save review");

    // update UI
    $('review-extra').style.display = 'none';
    $('review-status').style.display = 'block';
    $('review-status').textContent = `Decision: ${currentReviewDecision} saved!`;
    updateStepBadge(5, true);

    $('live-verification-area').style.display = '';
  } catch (e) {
    showLiveError(e.message);
  }
}

async function submitVerification(status) {
  const evidence = $('verify-evidence').value.trim();
  try {
    const res = await fetch('/api/verify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ session_id: currentLiveCaseId, status, evidence })
    });
    if (!res.ok) throw new Error("Could not save verification");

    $('verify-status').style.display = 'block';
    $('verify-status').textContent = `Status: ${status} recorded.`;
    updateStepBadge(6, true);

    // Final Summary
    $('live-complete-area').style.display = '';
    const root = currentDiagnosisRecord?.parsed_diagnosis?.root_cause || '(Manual Review)';
    $('summary-text').innerHTML = `<strong>Case:</strong> ${esc(currentLiveCaseId)}<br><br><strong>Diagnosis:</strong> ${esc(root)}<br><br><strong>Human Decision:</strong> ${esc(currentReviewDecision)}<br><br><strong>Packet Tracer Verification:</strong> ${status}`;

  } catch (e) {
    showLiveError(e.message);
  }
}

function toggleRawJson() {
  const el = $('live-raw-json');
  el.style.display = el.style.display === 'none' ? 'block' : 'none';
}

function renderLiveResult(d, rawText) {
  $('live-result-area').style.display = '';
  $('live-root-cause').textContent = d.root_cause || '(not provided)';

  const conf = typeof d.confidence === 'number' ? d.confidence : 0;
  const confPct = Math.round(conf * 100);
  const confCol = confPct >= 70 ? 'var(--accepted-text)' : confPct >= 40 ? 'var(--edited-text)' : 'var(--rejected-text)';
  $('live-confidence').textContent = confPct + '%';
  $('live-confidence').style.color = confCol;
  $('live-confidence-bar').style.width = confPct + '%';
  $('live-confidence-bar').style.background = confCol;

  $('live-osi-layer').textContent = d.osi_layer || '(not specified)';

  const evList = Array.isArray(d.evidence) ? d.evidence : [String(d.evidence || '')];
  $('live-evidence').innerHTML = evList.map(e => `<li>${esc(e)}</li>`).join('') || '<li style="color:var(--text-muted)">No evidence listed.</li>';

  $('live-next-command').textContent = d.next_command || '—';

  const fixList = Array.isArray(d.fix_steps) ? d.fix_steps : [String(d.fix_steps || '')];
  $('live-fix-steps').innerHTML = fixList.map((s, i) => `<li><strong style="color:var(--accent)">${i + 1}.</strong> ${esc(s)}</li>`).join('') || '<li style="color:var(--text-muted)">No fix steps listed.</li>';

  $('live-raw-json').textContent = JSON.stringify(d, null, 2);
  $('live-raw-json').style.display = 'none';
  $('live-result-area').scrollIntoView({ behavior: 'smooth', block: 'start' });
}

/* ══════════════════════════════════════════════════════════════════════════
   VIEW 7 — HISTORY
══════════════════════════════════════════════════════════════════════════ */
async function loadHistory() {
  try {
    const res = await fetch('/api/sessions');
    if (!res.ok) throw new Error("Could not fetch sessions");
    const sessions = await res.json();
    const tbody = $('history-tbody');
    if (!tbody) return;

    if (Object.keys(sessions).length === 0) {
      tbody.innerHTML = '<tr><td colspan="7" style="text-align:center;color:var(--text-muted)">No troubleshooting history available.</td></tr>';
      return;
    }

    const rows = Object.values(sessions)
      .sort((a, b) => (b.timestamp_created || '').localeCompare(a.timestamp_created || ''))
      .map(s => {
        const dStat = s.ai_diagnosis ? (s.ai_diagnosis.status === 'needs_manual_review' ? 'Needs Review' : 'Diagnosed') : 'Pending';
        const rDec = s.review ? s.review.decision : 'Pending';
        const vStat = s.verification ? s.verification.status : 'Pending';
        const sDate = new Date(s.timestamp_created).toLocaleString() || 'Unknown';
        return `<tr>
          <td class="mono">${esc(s.session_id)}</td>
          <td>${esc(sDate)}</td>
          <td>${esc((s.inputs?.symptom || '').substring(0, 40))}...</td>
          <td>${esc(dStat)}</td>
          <td>${decisionBadge(rDec)}</td>
          <td>${esc(vStat)}</td>
          <td><button class="diag-btn secondary" style="padding:2px 8px;font-size:10px" onclick="loadSessionHistoryView('${esc(s.session_id)}')">View/Reload</button></td>
        </tr>`;
      });

    tbody.innerHTML = rows.join('');
  } catch (e) {
    console.error("History fetch error:", e);
  }
}

async function loadSessionHistoryView(sessionId) {
  try {
    const res = await fetch('/api/sessions');
    const sessions = await res.json();
    const s = sessions[sessionId];
    if (!s) return;

    showView('diagnose');
    currentLiveCaseId = s.session_id;
    clearLiveForm();

    if (s.inputs) {
      $('diag-symptom').value = s.inputs.symptom || '';
      $('diag-topology').value = s.inputs.topology_note || '';
      $('diag-show-outputs').value = s.inputs.show_outputs || '';
    }

    if (s.ai_diagnosis) {
      currentDiagnosisRecord = s.ai_diagnosis;
      updateStepBadge(3, true); updateStepBadge(4, true);
      if (s.ai_diagnosis.status === 'needs_manual_review') {
        $('live-fallback-json').textContent = s.ai_diagnosis.raw_response;
        $('live-validation-area').style.display = '';
      } else {
        renderLiveResult(s.ai_diagnosis.parsed_diagnosis, s.ai_diagnosis.raw_response);
        $('live-review-area').style.display = '';
      }
    }

    if (s.review) {
      currentReviewDecision = s.review.decision;
      $('review-extra').style.display = 'none';
      $('review-status').style.display = 'block';
      $('review-status').textContent = `Decision: ${currentReviewDecision} loaded from history.`;

      if (s.review.edited_diagnosis) {
        $('review-status').innerHTML += `<div style="margin-top:10px;padding:10px;background:rgba(251,191,36,0.1);border:1px solid rgba(251,191,36,0.3);border-radius:4px;color:rgba(251,191,36,0.9);font-size:11px">
            <strong>Human Corrected Diagnosis:</strong><br>
            Root Cause: ${esc(s.review.edited_diagnosis.root_cause)}<br>
            OSI Layer: ${esc(s.review.edited_diagnosis.osi_layer)}<br>
            Next Command: ${esc(s.review.edited_diagnosis.next_command)}
         </div>`;
      }

      updateStepBadge(5, true);
      $('live-verification-area').style.display = '';
    }

    if (s.verification) {
      $('verify-evidence').value = s.verification.evidence || '';
      $('verify-status').style.display = 'block';
      $('verify-status').textContent = `Status: ${s.verification.status} recorded.`;
      updateStepBadge(6, true);
      $('live-complete-area').style.display = '';
      const root = s.ai_diagnosis?.parsed_diagnosis?.root_cause || '(Manual Review)';
      $('summary-text').innerHTML = `<strong>Case:</strong> ${esc(currentLiveCaseId)}<br><br><strong>Diagnosis:</strong> ${esc(root)}<br><br><strong>Human Decision:</strong> ${esc(currentReviewDecision)}<br><br><strong>Packet Tracer Verification:</strong> ${s.verification.status}`;
    }

    $('live-session-id').textContent = `Active Session: ${currentLiveCaseId}`;

  } catch (e) {
    console.error(e);
  }
}



/* ══════════════════════════════════════════════════════════════════════════
   RESPONSIVE — window resize
══════════════════════════════════════════════════════════════════════════ */
let _resizeTimer = null;
window.addEventListener('resize', () => {
  clearTimeout(_resizeTimer);
  _resizeTimer = setTimeout(resizeCharts, 120);
});

/* ══════════════════════════════════════════════════════════════════════════
   INIT
══════════════════════════════════════════════════════════════════════════ */
document.addEventListener('DOMContentLoaded', () => {
  renderOverview();
  renderCaseList();
  renderHumanReview();
  renderResponsibleAI();
  renderWorkflow();

  /* Ensure overview is active on initial load */
  showView('overview');
});
