"""
dashboard/build_data_bridge.py
-------------------------------
TASK-014 presentation-only data bridge.

Reads the existing source-of-truth files WITHOUT modifying them:
  - data/cases.csv
  - data/rule_results.json
  - data/diagnoses.json
  - data/review_log.csv
  - dashboard/dashboard_data.json

Writes a single presentation-only derived artifact:
  - dashboard/data.js   (window.NETSAGE_DATA object for browser)

This script is safe to re-run at any time. It never modifies the
source files. The generated data.js is excluded from git via
.gitignore (see the line added there), or can be committed as a
presentation artifact if desired.

Usage (from project root):
    python dashboard/build_data_bridge.py
"""

import os
import sys
import json
import re

# ── resolve project root regardless of where we run from ──────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)

CASES_CSV        = os.path.join(ROOT, "data", "cases.csv")
RULE_RESULTS     = os.path.join(ROOT, "data", "rule_results.json")
DIAGNOSES        = os.path.join(ROOT, "data", "diagnoses.json")
REVIEW_LOG       = os.path.join(ROOT, "data", "review_log.csv")
DASHBOARD_DATA   = os.path.join(SCRIPT_DIR, "dashboard_data.json")
OUT_JS           = os.path.join(SCRIPT_DIR, "data.js")


def read_csv_as_records(path: str) -> list:
    """Read a CSV into a list of dicts. stdlib only — no pandas needed."""
    import csv
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return [dict(row) for row in reader]


def read_json(path: str):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def build():
    # ── sanity-check source files ──────────────────────────────────────
    for p in (CASES_CSV, RULE_RESULTS, DIAGNOSES, REVIEW_LOG, DASHBOARD_DATA):
        if not os.path.exists(p):
            print(f"ERROR: required source file not found: {p}", file=sys.stderr)
            sys.exit(1)

    # ── read source data ────────────────────────────────────────────────
    cases        = read_csv_as_records(CASES_CSV)
    rule_results = read_json(RULE_RESULTS)
    diagnoses    = read_json(DIAGNOSES)
    review_log   = read_csv_as_records(REVIEW_LOG)
    dashboard    = read_json(DASHBOARD_DATA)

    # ── build the combined presentation object ───────────────────────────
    netsage_data = {
        "dashboard": dashboard,
        "cases": cases,
        "ruleResults": rule_results,
        "diagnoses": diagnoses,
        "reviewLog": review_log,
    }

    # ── serialise to JS ─────────────────────────────────────────────────
    js_content = (
        "// AUTO-GENERATED by dashboard/build_data_bridge.py\n"
        "// Do NOT edit manually. Re-run the script to update.\n"
        "// Source files: data/cases.csv, data/rule_results.json,\n"
        "//               data/diagnoses.json, data/review_log.csv,\n"
        "//               dashboard/dashboard_data.json\n"
        "// None of those source files were modified by this script.\n\n"
        f"window.NETSAGE_DATA = {json.dumps(netsage_data, indent=2, ensure_ascii=False)};\n"
    )

    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write(js_content)

    decided = {r["decision"] for r in review_log}
    print(
        f"data.js written — {len(cases)} cases, "
        f"{len(diagnoses)} diagnoses, "
        f"{len(review_log)} review entries, "
        f"decisions seen: {sorted(decided)}"
    )


if __name__ == "__main__":
    build()
